spring:
  application:
    name: Dictionaryy
  datasource:
    url: jdbc:postgresql://localhost:5432/dictionary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  error:
    include-message: always

